# Generated by Django 3.2.6 on 2021-08-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='categories',
            field=models.ManyToManyField(through='gamerraterapi.GameCategories', to='gamerraterapi.Categories'),
        ),
        migrations.AlterField(
            model_name='games',
            name='time_to_play',
            field=models.IntegerField(),
        ),
    ]
