# Generated by Django 3.2.6 on 2021-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0002_auto_20210809_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='year_released',
            field=models.IntegerField(),
        ),
    ]
